//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentWCFConsumerDotNetFramework.StudentServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/StudentWcfService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HeaderInfo", Namespace="http://schemas.datacontract.org/2004/07/BO")]
    [System.SerializableAttribute()]
    public partial class HeaderInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallStatus {
            get {
                return this.CallStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.CallStatusField, value) != true)) {
                    this.CallStatusField = value;
                    this.RaisePropertyChanged("CallStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionID {
            get {
                return this.TransactionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionIDField, value) != true)) {
                    this.TransactionIDField = value;
                    this.RaisePropertyChanged("TransactionID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudentBO", Namespace="http://schemas.datacontract.org/2004/07/BO")]
    [System.SerializableAttribute()]
    public partial class StudentBO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private System.Nullable<int> Roll_numberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> MarksField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> Roll_number {
            get {
                return this.Roll_numberField;
            }
            set {
                if ((this.Roll_numberField.Equals(value) != true)) {
                    this.Roll_numberField = value;
                    this.RaisePropertyChanged("Roll_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<decimal> Marks {
            get {
                return this.MarksField;
            }
            set {
                if ((this.MarksField.Equals(value) != true)) {
                    this.MarksField = value;
                    this.RaisePropertyChanged("Marks");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudentServiceReference.IStudentService")]
    public interface IStudentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetData", ReplyAction="http://tempuri.org/IStudentService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetData", ReplyAction="http://tempuri.org/IStudentService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IStudentService/GetDataUsingDataContractResponse")]
        StudentWCFConsumerDotNetFramework.StudentServiceReference.CompositeType GetDataUsingDataContract(StudentWCFConsumerDotNetFramework.StudentServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IStudentService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<StudentWCFConsumerDotNetFramework.StudentServiceReference.CompositeType> GetDataUsingDataContractAsync(StudentWCFConsumerDotNetFramework.StudentServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/Welcome", ReplyAction="http://tempuri.org/IStudentService/WelcomeResponse")]
        string Welcome();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/Welcome", ReplyAction="http://tempuri.org/IStudentService/WelcomeResponse")]
        System.Threading.Tasks.Task<string> WelcomeAsync();
        
        // CODEGEN: Generating message contract since the wrapper name (StudentInfoRequest) of message StudentInfoRequest does not match the default value (CreateStudent)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/CreateStudent", ReplyAction="http://tempuri.org/IStudentService/CreateStudentResponse")]
        StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoResponse CreateStudent(StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/CreateStudent", ReplyAction="http://tempuri.org/IStudentService/CreateStudentResponse")]
        System.Threading.Tasks.Task<StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoResponse> CreateStudentAsync(StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (StudentInfoRequest) of message StudentInfoRequest does not match the default value (UpdateStudent)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/UpdateStudent", ReplyAction="http://tempuri.org/IStudentService/UpdateStudentResponse")]
        StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoResponse UpdateStudent(StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/UpdateStudent", ReplyAction="http://tempuri.org/IStudentService/UpdateStudentResponse")]
        System.Threading.Tasks.Task<StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoResponse> UpdateStudentAsync(StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (StudentInfoRequest) of message StudentInfoRequest does not match the default value (DeleteStudent)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/DeleteStudent", ReplyAction="http://tempuri.org/IStudentService/DeleteStudentResponse")]
        StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoResponse DeleteStudent(StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/DeleteStudent", ReplyAction="http://tempuri.org/IStudentService/DeleteStudentResponse")]
        System.Threading.Tasks.Task<StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoResponse> DeleteStudentAsync(StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StudentInfoRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class StudentInfoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public StudentWCFConsumerDotNetFramework.StudentServiceReference.HeaderInfo Header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentBO Body;
        
        public StudentInfoRequest() {
        }
        
        public StudentInfoRequest(StudentWCFConsumerDotNetFramework.StudentServiceReference.HeaderInfo Header, StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentBO Body) {
            this.Header = Header;
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StudentInfoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class StudentInfoResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public StudentWCFConsumerDotNetFramework.StudentServiceReference.HeaderInfo Header;
        
        public StudentInfoResponse() {
        }
        
        public StudentInfoResponse(StudentWCFConsumerDotNetFramework.StudentServiceReference.HeaderInfo Header) {
            this.Header = Header;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentServiceChannel : StudentWCFConsumerDotNetFramework.StudentServiceReference.IStudentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentServiceClient : System.ServiceModel.ClientBase<StudentWCFConsumerDotNetFramework.StudentServiceReference.IStudentService>, StudentWCFConsumerDotNetFramework.StudentServiceReference.IStudentService {
        
        public StudentServiceClient() {
        }
        
        public StudentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public StudentWCFConsumerDotNetFramework.StudentServiceReference.CompositeType GetDataUsingDataContract(StudentWCFConsumerDotNetFramework.StudentServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<StudentWCFConsumerDotNetFramework.StudentServiceReference.CompositeType> GetDataUsingDataContractAsync(StudentWCFConsumerDotNetFramework.StudentServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string Welcome() {
            return base.Channel.Welcome();
        }
        
        public System.Threading.Tasks.Task<string> WelcomeAsync() {
            return base.Channel.WelcomeAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoResponse StudentWCFConsumerDotNetFramework.StudentServiceReference.IStudentService.CreateStudent(StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoRequest request) {
            return base.Channel.CreateStudent(request);
        }
        
        public void CreateStudent(ref StudentWCFConsumerDotNetFramework.StudentServiceReference.HeaderInfo Header, StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentBO Body) {
            StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoRequest inValue = new StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoRequest();
            inValue.Header = Header;
            inValue.Body = Body;
            StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoResponse retVal = ((StudentWCFConsumerDotNetFramework.StudentServiceReference.IStudentService)(this)).CreateStudent(inValue);
            Header = retVal.Header;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoResponse> StudentWCFConsumerDotNetFramework.StudentServiceReference.IStudentService.CreateStudentAsync(StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoRequest request) {
            return base.Channel.CreateStudentAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoResponse> CreateStudentAsync(StudentWCFConsumerDotNetFramework.StudentServiceReference.HeaderInfo Header, StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentBO Body) {
            StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoRequest inValue = new StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoRequest();
            inValue.Header = Header;
            inValue.Body = Body;
            return ((StudentWCFConsumerDotNetFramework.StudentServiceReference.IStudentService)(this)).CreateStudentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoResponse StudentWCFConsumerDotNetFramework.StudentServiceReference.IStudentService.UpdateStudent(StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoRequest request) {
            return base.Channel.UpdateStudent(request);
        }
        
        public void UpdateStudent(ref StudentWCFConsumerDotNetFramework.StudentServiceReference.HeaderInfo Header, StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentBO Body) {
            StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoRequest inValue = new StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoRequest();
            inValue.Header = Header;
            inValue.Body = Body;
            StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoResponse retVal = ((StudentWCFConsumerDotNetFramework.StudentServiceReference.IStudentService)(this)).UpdateStudent(inValue);
            Header = retVal.Header;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoResponse> StudentWCFConsumerDotNetFramework.StudentServiceReference.IStudentService.UpdateStudentAsync(StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoRequest request) {
            return base.Channel.UpdateStudentAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoResponse> UpdateStudentAsync(StudentWCFConsumerDotNetFramework.StudentServiceReference.HeaderInfo Header, StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentBO Body) {
            StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoRequest inValue = new StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoRequest();
            inValue.Header = Header;
            inValue.Body = Body;
            return ((StudentWCFConsumerDotNetFramework.StudentServiceReference.IStudentService)(this)).UpdateStudentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoResponse StudentWCFConsumerDotNetFramework.StudentServiceReference.IStudentService.DeleteStudent(StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoRequest request) {
            return base.Channel.DeleteStudent(request);
        }
        
        public void DeleteStudent(ref StudentWCFConsumerDotNetFramework.StudentServiceReference.HeaderInfo Header, StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentBO Body) {
            StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoRequest inValue = new StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoRequest();
            inValue.Header = Header;
            inValue.Body = Body;
            StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoResponse retVal = ((StudentWCFConsumerDotNetFramework.StudentServiceReference.IStudentService)(this)).DeleteStudent(inValue);
            Header = retVal.Header;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoResponse> StudentWCFConsumerDotNetFramework.StudentServiceReference.IStudentService.DeleteStudentAsync(StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoRequest request) {
            return base.Channel.DeleteStudentAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoResponse> DeleteStudentAsync(StudentWCFConsumerDotNetFramework.StudentServiceReference.HeaderInfo Header, StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentBO Body) {
            StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoRequest inValue = new StudentWCFConsumerDotNetFramework.StudentServiceReference.StudentInfoRequest();
            inValue.Header = Header;
            inValue.Body = Body;
            return ((StudentWCFConsumerDotNetFramework.StudentServiceReference.IStudentService)(this)).DeleteStudentAsync(inValue);
        }
    }
}
